// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFaN-2a5kT2urbjH5IlJHcK1pToNEqm_4',
    appId: '1:431329206027:web:d0ecaaac9c941f15a48c0e',
    messagingSenderId: '431329206027',
    projectId: 'kafaat-61a6d',
    authDomain: 'kafaat-61a6d.firebaseapp.com',
    storageBucket: 'kafaat-61a6d.appspot.com',
    measurementId: 'G-KKXR5G4KNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5SZPZ4Rewosuz0FShDiAL9cG1wpPOivY',
    appId: '1:431329206027:android:4e07076990127294a48c0e',
    messagingSenderId: '431329206027',
    projectId: 'kafaat-61a6d',
    storageBucket: 'kafaat-61a6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl-gsx4PcVk1KK0lzSvehl9FOeK-RYqMA',
    appId: '1:431329206027:ios:390e928fa5c6af9ca48c0e',
    messagingSenderId: '431329206027',
    projectId: 'kafaat-61a6d',
    storageBucket: 'kafaat-61a6d.appspot.com',
    iosBundleId: 'com.tqniait.kafaat',
  );
}
